<?php

/**
 * @file
 * Provides a work entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function md_worksheet_theme() {
  return [
    'work' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for work templates.
 *
 * Default template: work.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the work information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_work(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
